#!/usr/bin/env bash
#
# Package the rendered voice auditions and publish them as a release asset.
#
# The clips take about a day of Kokoro inference to produce, so they are
# rendered once on a developer's machine rather than in CI, and published
# under their own tag: the app's releases should not have to carry 271 MB
# that changes only when the voice catalogue does.
#
# Usage: scripts/publish-previews.sh [tag]
set -euo pipefail

TAG="${1:-previews-v1}"
REPO="crscarolina/kindle-ai-export"
SRC="${PREVIEWS_DIR:-$HOME/Library/Application Support/kindle-ai-export/previews}"
EXPECTED_CLIPS=224

if [[ ! -d "$SRC" ]]; then
  echo "no previews at $SRC" >&2
  exit 1
fi

count=$(find "$SRC" -name '*.m4b' -type f | wc -l | tr -d ' ')
if [[ "$count" -lt "$EXPECTED_CLIPS" ]]; then
  echo "only $count of $EXPECTED_CLIPS clips rendered; wait for the render to finish" >&2
  echo "(override with EXPECTED_CLIPS=$count if that is deliberate)" >&2
  [[ "${EXPECTED_CLIPS:-}" == "$count" ]] || exit 1
fi

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
staging="$work/voice-previews"
mkdir -p "$staging"

# Only the clips. The manifest is regenerated by `list-voices.ts` and a stray
# staging directory would inflate the download for no reason.
find "$SRC" -name '*.m4b' -type f -exec cp {} "$staging/" \;

archive="$work/voice-previews.zip"
ditto -c -k --sequesterRsrc --keepParent "$staging" "$archive"

sha=$(shasum -a 256 "$archive" | cut -d' ' -f1)
size=$(du -h "$archive" | cut -f1)

echo "clips:    $count"
echo "archive:  $archive ($size)"
echo "sha256:   $sha"
echo

if ! gh release view "$TAG" --repo "$REPO" >/dev/null 2>&1; then
  gh release create "$TAG" --repo "$REPO" \
    --title "Voice previews" \
    --notes "Audition clips for every Kokoro voice at every pace offered in the app: $count files, one per voice and speed.

Downloaded by the app on first use rather than bundled -- the clips are identical on both architectures, and most readers audition a handful. Published under its own tag so app releases do not have to carry them.

Rendered by \`src/render-voice-previews.ts\`. sha256 of the archive is pinned in \`app/Sources/KindleExportCore/PreviewLibrary.swift\`."
fi

gh release upload "$TAG" "$archive" --repo "$REPO" --clobber

echo
echo "Now pin this in app/Sources/KindleExportCore/PreviewLibrary.swift:"
echo "  sha256: \"$sha\","
echo "  clipCount: $count)"
